sphinx:
  services:
    - image:ada-trainings
  stage: build
  script:
      - make doc_html
  artifacts:
    name: "HTML_doc"
    paths:
      - doc/_build/html/*

check_builds:
  services:
    - image:ada-trainings
  stage: build
  script:
    - export ADAFLAGS="-Werror"
    - make build_solutions
    - make build_problems

check_templates:
  services:
    - image:ada-trainings
  stage: test
  script:
    - cp -r src src.actual
    - make generate
    - diff -rb src.actual src

lint:
  services:
    - image:lint
  stage: test
  script:
    - autolint --output-code-climate-report code_quality_report.json .
  artifacts:
    when: always
    reports:
      codequality: code_quality_report.json
