sphinx:
  services:
    - image:ada-trainings
  stage: build
  script:
      - make doc_html
  artifacts:
    name: "HTML_doc"
    paths:
      - doc/_build/html/*

check_builds:
  services:
    - image:ada-trainings
  stage: build
  script:
    - cp -r $HOME/mage* $HOME/.local/share/alire/releases/
    - export ADAFLAGS="-Werror"
    - make build_solutions
    - make build_problems

check_templates:
  services:
    - image:ada-trainings
  stage: test
  script:
    - cp -r src src.actual
    - make generate
    - diff -rb src.actual src 
