sphinx:
  services:
    - image:ada-trainings
  stage: build
  script:
      - make doc_html

solutions:
  services:
    - image:ada-trainings
  stage: build
  script:
    - mkdir -p alire/cache/
    - cp -r $HOME/mage_*/alire/cache/dependencies alire/cache
    - cp -r $HOME/mage_* alire/cache/dependencies
    - make build_solutions

check_templates:
  services:
    - image:ada-trainings
  stage: test
  script:
    - cp -r src src.actual
    - make generate
    - diff -rb src.actual src 
