name = "labs_solar_system"
description = "A set of SDL-based exercises to learn Ada"
version = "0.1.0-dev"

authors = ["Léo Germond"]
maintainers = ["Léo Germond <germond@adacore.com>"]
maintainers-logins = ["leogermond"]

licenses = "GPL-3.0-or-later"
executables = ["getting_started_main"]
[[depends-on]]
mage = "~0.5.0"
