name = "labs_solar_system"
description = "A set of SDL-based exercises to learn Ada"
version = "0.1.0-dev"

authors = ["Léo Germond"]
maintainers = ["Léo Germond <germond@adacore.com>"]
maintainers-logins = ["leogermond"]

executables = ["getting_started"]
[[depends-on]]
mage = "~0.5.0"
